// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZMwehuQiW8GaGrsOZTyMNGS8x7s2GXpU',
    appId: '1:339086197418:web:fce31a517e453361c0c6d3',
    messagingSenderId: '339086197418',
    projectId: 'not-defterim-2cabe',
    authDomain: 'not-defterim-2cabe.firebaseapp.com',
    storageBucket: 'not-defterim-2cabe.appspot.com',
    measurementId: 'G-HMEPTW6LCN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcm1hzdgj8aFCJlepb_9xGWbVU-qTWSBg',
    appId: '1:339086197418:android:0d87ffbf9f988180c0c6d3',
    messagingSenderId: '339086197418',
    projectId: 'not-defterim-2cabe',
    storageBucket: 'not-defterim-2cabe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0t6eAYFocf-9yhuO0sd4DnYYwuFjLwKk',
    appId: '1:339086197418:ios:7540acb82d32553fc0c6d3',
    messagingSenderId: '339086197418',
    projectId: 'not-defterim-2cabe',
    storageBucket: 'not-defterim-2cabe.appspot.com',
    iosBundleId: 'com.notdefterim.benimNotDefterim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0t6eAYFocf-9yhuO0sd4DnYYwuFjLwKk',
    appId: '1:339086197418:ios:7540acb82d32553fc0c6d3',
    messagingSenderId: '339086197418',
    projectId: 'not-defterim-2cabe',
    storageBucket: 'not-defterim-2cabe.appspot.com',
    iosBundleId: 'com.notdefterim.benimNotDefterim',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZMwehuQiW8GaGrsOZTyMNGS8x7s2GXpU',
    appId: '1:339086197418:web:366bcc4c58f23896c0c6d3',
    messagingSenderId: '339086197418',
    projectId: 'not-defterim-2cabe',
    authDomain: 'not-defterim-2cabe.firebaseapp.com',
    storageBucket: 'not-defterim-2cabe.appspot.com',
    measurementId: 'G-5CW3W0XJ7W',
  );
}
